### PR TITLE
Improve travis build

### PR DESCRIPTION
**Pull request by pascalgrimaud**
I use the same in the main generator-jhipster

The only "issue" is that the gradle build take ~10min. It's really too long, in my opinion. As I'm beginner with Gradle, I don't know how to optimize and speed up the build for gradle.
Maybe use a new repository like jhipster-travis-build to keep all lib (~/.gradle) ? But the repository can't be over than 1Go.

Although it take time, u can see the file generated at the end of travis build log.
Feel free to merge this or not :smile:

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Arghh the maven build failed :
`ls: cannot access target/asciidoc/pdf/: No such file or directory`

Don't understand why, in my travis build https://travis-ci.org/pascalgrimaud/generator-jhipster-swagger2markup/builds/98808862 it's OK

**Comment by atomfrede** [comment]
Cool! Yes the thing with gradle is, that it doesn't download its dependencies in parallel (which is a known issue since gradle 1.x).

**Comment by pascalgrimaud** [comment]
Found the problem => https://github.com/atomfrede/generator-jhipster-swagger2markup/commit/eb4f59b36dfdfc807b272866461fe385120bc90b

You removed the "pdf" by default. So I updated the test in the script

**Comment by atomfrede** [comment]
Oh yes, I think most common use case is html and not both (furthermore pdf generation takes a while)

**Pull request merged**
